wandb:
  entity: "wandb-japan"
  project: "ichikara-test"

inference_interval: 0 # seconds

model:
  artifact_path: null
  max_model_len: 3000
  chat_template: null
  dtype: 'float16'
  trust_remote_code: true
  device_map: "auto"
  load_in_8bit: false
  load_in_4bit: false

generator:
  top_p: 1.0
  temperature: 0.1
  max_tokens: 128

ichikara:
  data_path: "weave:///wandb-japan/ichikara-test/object/ichikara_100:yPVEtbjUl4ZZ2PhlFimjbq7LD3llfChQYXeMJCtoOPU"
  auto_eval_model: "gpt-4-0613"
  upload_human_evaled_file: # After conducting human evaluation, add the path to the CSV file.

sample_dataset:
  artifacts_path: "your artifact path here"
  # add necessary configration here