wandb:
  run_name: "matsuo-lab/weblab-10b-instruction-sft" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
num_gpus: 2
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "matsuo-lab/weblab-10b-instruction-sft" #if you use openai api, put the name of model
  chat_template: "matsuo-lab/weblab-10b-instruction-sft"
  size_category: "10B≤ <30B"
  size: 10711851008
  release_date: "8/18/2024"