wandb:
  run_name: "stabilityai/japanese-stablelm-2-instruct-1_6b" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
num_gpus: 1
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "stabilityai/japanese-stablelm-2-instruct-1_6b" #if you use openai api, put the name of model
  chat_template: "stabilityai/japanese-stablelm-2-instruct-1_6b"
  size_category: "<10B"
  size: 1644515328
  release_date: "5/9/2024"
  max_model_len: 3200