wandb:
  run_name: "cyberagent/calm2-7b-chat-dpo-experimental" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "cyberagent/calm2-7b-chat-dpo-experimental" #if you use openai api, put the name of model
  chat_template: "cyberagent/calm2-7b-chat-dpo-experimental"
  size_category: "<10B"
  size: 7008948224
  release_date: "1/24/2024"

