wandb:
  run_name: "augmxnt/shisa-gamma-7b-v1" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
num_gpus: 1
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  max_model_len: 3500 # update 
  pretrained_model_name_or_path: "augmxnt/shisa-gamma-7b-v1" #if you use openai api, put the name of model
  chat_template: "augmxnt/shisa-gamma-7b-v1"
  size_category: "<10B"
  size: 7241732096
  release_date: "12/24/2023"
