wandb:
  run_name: "stockmark/stockmark-100b-instruct-v0.1" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
num_gpus: 4
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "stockmark/stockmark-100b-instruct-v0.1" #if you use openai api, put the name of model
  chat_template: "stockmark/stockmark-100b-instruct-v0.1"
  size_category: "30B≤"
  size: 98251629568
  release_date: "5/16/2024"