wandb:
  run_name: "SakanaAI/EvoLLM-JP-v1-7B" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  max_model_len: 3500 # update 
  pretrained_model_name_or_path: "SakanaAI/EvoLLM-JP-v1-7B" #if you use openai api, put the name of model
  chat_template: "SakanaAI/EvoLLM-JP-v1-7B"
  size_category: "<10B"
  size: 7241732096
  release_date: "3/21/2024"