wandb:
  run_name: "Qwen/Qwen1.5-72B-Chat" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
num_gpus: 2
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "Qwen/Qwen1.5-72B-Chat" #if you use openai api, put the name of model
  chat_template: "Qwen/Qwen1.5-72B-Chat"
  size_category: "30B≤"
  size: 72287920128
  release_date: "2/4/2023"