wandb:
  run_name: "stabilityai/StableBeluga-7B" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "stabilityai/StableBeluga-7B" #if you use openai api, put the name of model
  chat_template: "stabilityai/StableBeluga-7B"
  size_category: "<10B"
  size: 6738415616
  release_date: "7/27/2023"