wandb:
  run_name: "anthoropic/claude-3-opus-20240229-v1:0" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: "amazon_bedrock"
batch_size: 1 # vllmは256, apiは32を推奨
inference_interval: 5 # seconds

model:
  pretrained_model_name_or_path: "anthropic.claude-3-opus-20240229-v1:0" #if you use openai api, put the name of model
  size_category: "api"
  size: null
  release_date: "2/29/2024"
