wandb:
  run_name: "mistralai/Mistral-7B-Instruct-v0.2" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "mistralai/Mistral-7B-Instruct-v0.2" #if you use openai api, put the name of model
  chat_template: "mistralai/Mistral-7B-Instruct-v0.2"
  size_category: "<10B"
  size: 7241732096
  release_date: "12/11/2023"